import type { KnowledgeDoc } from './types';

export const KNOWLEDGE_DOCS: KnowledgeDoc[] = [
  {
    id: 'case-ielts-reading-webapp',
    title: 'IELTS Reading WebApp Case',
    type: 'case',
    tags: ['ielts', 'learning-tool', 'vocabulary', 'wrong-answer-book', 'local-storage', '雅思', '生词本', '错题集'],
    aliases: ['雅思', '雅思阅读', '雅思听力', '生词本', '生词', '词库', '错题集', '错题', '同义替换', '阅读训练', '听力词汇'],
    useCases: ['语言学习工具', '本地复盘闭环', '生词和错题管理', '考试训练进度追踪'],
    summary: 'A local-first study tool for IELTS reading practice, vocabulary review, and wrong-answer tracking. 适合作为雅思生词、错题和阅读训练类 MVP 参考。',
    content: [
      'Context: IELTS learners need focused reading practice and review loops.',
      '中文说明：如果用户想做雅思生词、错题或阅读训练工具，V1 应先验证“记录 -> 复盘 -> 再练习”的闭环。',
      'MVP: passage list, question practice, vocabulary notes, wrong-answer book, local progress.',
      'Architecture: React + localStorage is enough for V1; no login or database.',
      'Acceptance: users can complete one passage, save mistakes, and revisit vocabulary.',
    ].join('\n'),
  },
  {
    id: 'case-prompteval-lab',
    title: 'PromptEval Lab Case',
    type: 'case',
    tags: ['prompt-evaluation', 'aigc', 'design-student', 'evaluation', 'versioning', '提示词评测', '版本对比'],
    aliases: ['提示词', 'prompt', '提示词评测', 'prompt 调优', 'AIGC', '设计学生', '生图', '图片生成', '版本对比', '评分标准'],
    useCases: ['提示词版本管理', 'AIGC 输出评测', '评分标准沉淀', '设计学习作品对比'],
    summary: 'A prompt evaluation workspace for design students comparing prompt versions and outputs. 适合提示词评测、调优和版本对比场景。',
    content: [
      'Context: design students need to compare prompt variants without building a full evaluation platform.',
      '中文说明：提示词评测系统的 V1 重点是版本、输出、评分标准和对比，不应先做复杂团队协作。',
      'MVP: prompt version list, output notes, rubric scoring, simple comparison table.',
      'Data: PromptVersion, EvaluationRun, ScoreDimension stored locally.',
      'Scope control: no team workspace, no billing, no complex model routing in V1.',
    ].join('\n'),
  },
  {
    id: 'case-ai-customer-service-evaluation',
    title: 'AI Customer Service Evaluation Case',
    type: 'case',
    tags: ['ai-customer-service', 'llm-evaluation', 'response-quality', 'rubric', 'AI 客服', '质检'],
    aliases: ['AI 客服', '客服回复', '回复质量', '大模型评测', 'LLM 评测', '质检', '话术', '回复改写'],
    useCases: ['客服话术质检', '大模型回答评分', '回复改写建议', '服务质量评估'],
    summary: 'A rubric-based evaluator for AI customer service response quality. 适合 AI 客服回复质检和话术改写类产品。',
    content: [
      'Context: operators need consistent checks for AI customer support answers.',
      '中文说明：客服评测类 V1 应强调评分证据、问题定位和可执行改写建议。',
      'MVP: paste conversation, score response quality, show issue list, suggest rewrite.',
      'Rubric: correctness, empathy, policy compliance, next-step clarity, escalation handling.',
      'Acceptance: every score must include evidence and a clear pass/fail explanation.',
    ].join('\n'),
  },
  {
    id: 'case-vibe-copilot',
    title: 'Vibe Copilot Case',
    type: 'case',
    tags: ['vibe-coding', 'codex', 'claude-code', 'developer-handoff', 'dev-spec', '开发交付', '产品构思'],
    aliases: ['vibe coding', 'Codex', 'Claude Code', 'Cursor', '开发提示词', 'DEV_SPEC', '产品构思', '产品规格', 'AI Coding', '开发交付'],
    useCases: ['开发交付包生成', '产品构思收敛', 'AI Coding 前置规格', 'Codex 开发提示词'],
    summary: 'A product framing copilot that turns vague product ideas into developer-ready handoff packages. 适合产品构思到开发规格的交付链路。',
    content: [
      'Context: vibe coding beginners often start coding before product scope is clear.',
      '中文说明：这类产品要把需求、范围、技术和验收标准转换成可执行 DEV_SPEC。',
      'MVP: idea diagnosis, MVP decision, tech decision, developer handoff.',
      'Handoff: Product Brief, MVP Scope, DEV_SPEC, architecture, data model, acceptance criteria, Codex prompt.',
      'Constraint: no database, no team features, no payment unless explicitly requested.',
    ].join('\n'),
  },
  {
    id: 'template-product-brief',
    title: 'Product Brief Template',
    type: 'prd-template',
    tags: ['product-brief', 'target-user', 'scenario', 'pain-point', '产品简介', '目标用户'],
    aliases: ['产品简介', '产品定位', '目标用户', '使用场景', '核心痛点', '产品目标'],
    useCases: ['产品定义', '目标用户澄清', '场景和痛点描述', 'V1 目标收敛'],
    summary: 'A compact product brief structure for V1 product definition. 用于把想法压缩成目标用户、场景、痛点和目标。',
    content: [
      'Required fields: product name, target user, scenario, pain point, product goal.',
      '中文说明：Product Brief 必须先说清楚谁、在什么场景、遇到什么问题、产品要达成什么目标。',
      'Good brief: says who has the problem, when it happens, why existing alternatives fail.',
      'V1 note: avoid broad personas such as everyone, creators, or businesses without a concrete scenario.',
    ].join('\n'),
  },
  {
    id: 'template-mvp-scope',
    title: 'MVP Scope Template',
    type: 'prd-template',
    tags: ['mvp', 'must-have', 'out-of-scope', 'scope-control', '第一版', '范围控制'],
    aliases: ['MVP', '第一版', '最小可行产品', 'Must Have', 'Should Have', 'Out of Scope', '不做什么', '范围控制'],
    useCases: ['V1 范围压缩', '功能优先级', 'Out of Scope 决策', '最小闭环定义'],
    summary: 'A V1 scope template that separates must-have, should-have, and out-of-scope features. 用于防止第一版范围膨胀。',
    content: [
      'Must Have: only features required for the first complete user loop.',
      '中文说明：MVP 不是功能清单，而是完成一个最小用户闭环所必需的能力。',
      'Should Have: useful improvements that can be skipped if time is limited.',
      'Out of Scope: login, payment, team collaboration, database, admin dashboard unless explicitly required.',
      'Scope test: if removing a feature still preserves the loop, it is not must-have.',
    ].join('\n'),
  },
  {
    id: 'template-dev-spec',
    title: 'DEV_SPEC Template',
    type: 'architecture-template',
    tags: ['dev-spec', 'technical-architecture', 'acceptance-criteria', 'implementation', '开发规格', '验收标准'],
    aliases: ['开发规格', '技术规格', '规格文档', 'DEV_SPEC', '页面结构', '数据模型', '验收标准'],
    useCases: ['开发规格生成', '页面结构定义', '数据模型说明', '验收标准补齐'],
    summary: 'A developer-facing specification structure for AI coding tools. 用于把产品方案变成可交给开发工具的规格文档。',
    content: [
      'Sections: overview, MVP scope, user flow, page structure, data model, core functions, AI behavior, acceptance, risks, implementation notes.',
      '中文说明：DEV_SPEC 要让开发工具知道页面、数据、函数、AI 行为和完成判断。',
      'A good DEV_SPEC turns product intent into file-level and testable implementation guidance.',
      'Use placeholders such as 待补充 when source information is missing.',
    ].join('\n'),
  },
  {
    id: 'template-codex-prompt',
    title: 'Codex Prompt Template',
    type: 'prompt-sample',
    tags: ['codex', 'development-prompt', 'implementation-task', 'testing', '开发任务', '测试命令'],
    aliases: ['Codex 提示词', 'Claude Code 提示词', 'Cursor 提示词', '开发任务', '测试命令', '实现约束'],
    useCases: ['AI 编程任务说明', '实现约束说明', '测试命令要求', '开发交付复制'],
    summary: 'A practical prompt format for Codex, Claude Code, or Cursor implementation tasks. 用于把 DEV_SPEC 转成可执行开发任务。',
    content: [
      'Prompt must include: task, existing context, files to inspect, constraints, implementation steps, acceptance criteria, test command.',
      '中文说明：开发提示词要明确任务、限制、验收标准和测试命令，避免 AI 编程工具过度发挥。',
      'Prompt must say what not to do: no database, no auth, no payment, no unrelated refactor unless requested.',
      'Prompt should ask the coding tool to run build/tests and report changed files.',
    ].join('\n'),
  },
];
